<a href="https://colab.research.google.com/github/sadichyaa/Assesment1/blob/main/Worksheet0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **4 TO - DO - Task**
Please complete all the problem listed below.


## **4.1 Exercise on Functions:**
Task - 1:

Create a Python program that converts between different units of measurement.

• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.

• Requirements:

1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.

• Conversion Options:

1. Length:

– Convert meters (m) to feet (ft).

– Convert feet (ft) to meters (m).

2. Weight:

– Convert kilograms (kg) to pounds (lbs).

– Convert pounds (lbs) to kilograms (kg).

3. Volume:

– Convert liters (L) to gallons (gal).

– Convert gallons (gal) to liters (L).


In [ ]:
def convert_units(conversion_type, value):
    """
    Convert units based on the selected conversion type.

    Parameters:
    conversion_type (int): The conversion option chosen by the user.
    value (float): The numeric value to convert.

    Returns:
    float: The converted value.
    """

    if conversion_type == 1:  # meters to feet
        return value * 3.28084
    elif conversion_type == 2:  # feet to meters
        return value / 3.28084
    elif conversion_type == 3:  # kg to pounds
        return value * 2.20462
    elif conversion_type == 4:  # pounds to kg
        return value / 2.20462
    elif conversion_type == 5:  # liters to gallons
        return value * 0.264172
    elif conversion_type == 6:  # gallons to liters
        return value / 0.264172
    else:
        return None


def main():
    print("Unit Conversion Program")
    print("1. Meters to Feet")
    print("2. Feet to Meters")
    print("3. Kilograms to Pounds")
    print("4. Pounds to Kilograms")
    print("5. Liters to Gallons")
    print("6. Gallons to Liters")

    try:
        choice = int(input("Choose conversion type (1-6): "))
        value = float(input("Enter the value to convert: "))

        result = convert_units(choice, value)

        if result is None:
            print("Unsupported conversion type.")
        else:
            print("Converted value:", result)

    except ValueError:
        print("Invalid input! Please enter numeric values.")


main()

Unit Conversion Program
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Choose conversion type (1-6): 5
Enter the value to convert: 10
Converted value: 2.6417200000000003


## **Task - 2:**
Create a Python program that performs various mathematical operations on a list of numbers.

• The Program should:

1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).

2. Ask the user to input a list of numbers (separated by spaces).

3. Perform the selected operation and display the result.

4. Handle potential errors, such as invalid input or empty lists.

• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).

3. User Input: Prompt the user to select the operation and input the list of numbers.

4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [ ]:
def find_sum(numbers):
    """
    Calculate the sum of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The sum of the numbers.
    """
    return sum(numbers)


def find_average(numbers):
    """
    Calculate the average of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The average value.
    """
    return sum(numbers) / len(numbers)


def find_maximum(numbers):
    """
    Find the maximum value in a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The maximum value.
    """
    return max(numbers)


def find_minimum(numbers):
    """
    Find the minimum value in a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The minimum value.
    """
    return min(numbers)


def main():
    print("Mathematical Operations on a List")
    print("1. Find Sum")
    print("2. Find Average")
    print("3. Find Maximum")
    print("4. Find Minimum")

    try:
        choice = int(input("Choose an operation (1-4): "))
        user_input = input("Enter numbers separated by spaces: ")

        numbers = [float(num) for num in user_input.split()]

        if len(numbers) == 0:
            print("Error: The list cannot be empty.")
            return

        if choice == 1:
            print("Sum:", find_sum(numbers))
        elif choice == 2:
            print("Average:", find_average(numbers))
        elif choice == 3:
            print("Maximum:", find_maximum(numbers))
        elif choice == 4:
            print("Minimum:", find_minimum(numbers))
        else:
            print("Invalid operation choice.")

    except ValueError:
        print("Invalid input! Please enter numeric values only.")


main()

Mathematical Operations on a List
1. Find Sum
2. Find Average
3. Find Maximum
4. Find Minimum
Choose an operation (1-4): 2
Enter numbers separated by spaces: 10 20 30 40
Average: 25.0


### **4.2 Exercise on List Manipulation:**

1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.

• Requirements:

– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

2. Slice a Sublist:

Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

• Requirements:

– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).

– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].


3. Reverse a List Using Slicing:

Write a Python function that reverses a list using slicing.

• Requirements:

– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

4. Remove the First and Last Elements:

Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

• Requirements:

– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

5. Get the First n Elements:

Write a Python function that extracts the first n elements from a list.

• Requirements:

– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.

– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.

• Requirements:

– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.

– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

7. Extract Elements in Reverse Order:

Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

• Requirements:
– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [ ]:
# 1. Extract Every Other Element
def extract_every_other(lst):
    """
    Return every other element from the list starting from the first element.

    Parameters:
    lst (list): Input list.

    Returns:
    list: List containing every other element.
    """
    return lst[::2]


# 2. Slice a Sublist
def get_sublist(lst, start, end):
    """
    Return a sublist from start index to end index (inclusive).

    Parameters:
    lst (list): Input list
    start (int): Starting index
    end (int): Ending index

    Returns:
    list: Sublist from start to end
    """
    return lst[start:end+1]


# 3. Reverse a List Using Slicing
def reverse_list(lst):
    """
    Return the reversed version of the list using slicing.

    Parameters:
    lst (list): Input list

    Returns:
    list: Reversed list
    """
    return lst[::-1]


# 4. Remove the First and Last Elements
def remove_first_last(lst):
    """
    Remove the first and last elements from a list.

    Parameters:
    lst (list): Input list

    Returns:
    list: List without first and last elements
    """
    return lst[1:-1]


# 5. Get the First n Elements
def get_first_n(lst, n):
    """
    Return the first n elements of the list.

    Parameters:
    lst (list): Input list
    n (int): Number of elements to extract

    Returns:
    list: First n elements
    """
    return lst[:n]


# 6. Extract Last n Elements
def get_last_n(lst, n):
    """
    Return the last n elements of the list.

    Parameters:
    lst (list): Input list
    n (int): Number of elements

    Returns:
    list: Last n elements
    """
    return lst[-n:]


# 7. Extract Elements in Reverse Order Skipping One
def reverse_skip(lst):
    """
    Return every second element starting from the second-to-last
    element while moving backward.

    Parameters:
    lst (list): Input list

    Returns:
    list: Elements extracted in reverse with skipping
    """
    return lst[-2::-2]


# Example usage
numbers = [1, 2, 3, 4, 5, 6]

print("Every other:", extract_every_other(numbers))
print("Sublist:", get_sublist(numbers, 2, 4))
print("Reversed:", reverse_list(numbers))
print("Remove first & last:", remove_first_last(numbers))
print("First 3:", get_first_n(numbers, 3))
print("Last 2:", get_last_n(numbers, 2))
print("Reverse skip:", reverse_skip(numbers))

Every other: [1, 3, 5]
Sublist: [3, 4, 5]
Reversed: [6, 5, 4, 3, 2, 1]
Remove first & last: [2, 3, 4, 5]
First 3: [1, 2, 3]
Last 2: [5, 6]
Reverse skip: [5, 3, 1]


4.3 Exercise on Nested List:

1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

• Requirements:

– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.

– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.

• Requirements:

– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.

– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

3. Sum of All Elements in a Nested List:

Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

• Requirements:

– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

4. Remove Specific Element from a Nested List:

Write a Python function that removes all occurrences of a specific element from a nested list.

• Requirements:

– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.

– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].


5. Find the Maximum Element in a Nested List:

Write a Python function that finds the maximum element in a nested list (regardless of depth).

• Requirements:

– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

6. Count Occurrences of an Element in a Nested List:

Write a Python function that counts how many times a specific element appears in a nested list.

• Requirements:

– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.

– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.


7. Flatten a List of Lists of Lists:

Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

• Requirements:

– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.

– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].


8. Nested List Average:

Write a Python function that calculates the average of all elements in a nested list.

• Requirements:

– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.

– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [ ]:
# 1. Flatten a Nested List
def flatten(lst):
    """
    Flatten a nested list into a single list (one level).

    Parameters:
    lst (list): A nested list.

    Returns:
    list: Flattened list.
    """
    result = []
    for sub in lst:
        result.extend(sub)
    return result


# 2. Access Nested Element
def access_nested_element(lst, indices):
    """
    Access an element from a nested list using a list of indices.

    Parameters:
    lst (list): Nested list
    indices (list): List of indices

    Returns:
    element: Element at the given position
    """
    element = lst
    for i in indices:
        element = element[i]
    return element


# 3. Sum of All Elements in a Nested List
def sum_nested(lst):
    """
    Calculate the sum of all numbers in a nested list.

    Parameters:
    lst (list): Nested list

    Returns:
    int/float: Sum of all elements
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total


# 4. Remove Specific Element
def remove_element(lst, elem):
    """
    Remove all occurrences of elem from a nested list.

    Parameters:
    lst (list): Nested list
    elem (value): Element to remove

    Returns:
    list: Modified list
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result


# 5. Find Maximum Element
def find_max(lst):
    """
    Find the maximum element in a nested list.

    Parameters:
    lst (list): Nested list

    Returns:
    number: Maximum value
    """
    max_val = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_val = max(max_val, find_max(item))
        else:
            max_val = max(max_val, item)
    return max_val


# 6. Count Occurrences
def count_occurrences(lst, elem):
    """
    Count occurrences of elem in a nested list.

    Parameters:
    lst (list): Nested list
    elem (value): Element to count

    Returns:
    int: Number of occurrences
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count


# 7. Deep Flatten
def deep_flatten(lst):
    """
    Flatten a deeply nested list into a single list.

    Parameters:
    lst (list): Deeply nested list

    Returns:
    list: Completely flattened list
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result


# 8. Average of Nested List
def average_nested(lst):
    """
    Calculate the average of all elements in a nested list.

    Parameters:
    lst (list): Nested list

    Returns:
    float: Average value
    """
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)


# Example Usage
data = [[1, 2], [3, [4, 5]], 6]

print("Flatten:", flatten([[1,2],[3,4],[5]]))
print("Access element:", access_nested_element([[1,2,3],[4,5,6],[7,8,9]],[1,2]))
print("Sum nested:", sum_nested(data))
print("Remove element:", remove_element([[1,2],[3,2],[4,5]],2))
print("Max element:", find_max(data))
print("Count occurrences:", count_occurrences([[1,2],[2,3],[2,4]],2))
print("Deep flatten:", deep_flatten([[[1,2],[3,4]],[[5,6],[7,8]]]))
print("Average:", average_nested([[1,2],[3,4],[5,6]]))

Flatten: [1, 2, 3, 4, 5]
Access element: 6
Sum nested: 21
Remove element: [[1], [3], [4, 5]]
Max element: 6
Count occurrences: 3
Deep flatten: [1, 2, 3, 4, 5, 6, 7, 8]
Average: 3.5


## **10 To - Do - NumPy**
Please complete all the problems listed below:

### **10.1 Basic Vector and Matrix Operation with Numpy.**

Problem - 1: Array Creation:

Complete the following Tasks:

1. Initialize an empty array with size 2X2.

2. Initialize an all one array with size 4X2.

3. Return a new array of given shape and type, filled with fill value.

{Hint: np.full}

4. Return a new array of zeros with same shape and type as a given array.

{Hint: np.zeros like}

5. Return a new array of ones with same shape and type as a given array.

{Hint: np.ones like}

6. For an existing list new_list = [1,2,3,4] convert to an numpy array.

{Hint: np.array()}

Problem - 2: Array Manipulation:

Numerical Ranges and Array indexing:

Complete the following tasks:

1. Create an array with values ranging from 10 to 49.

{Hint:np.arrange()}.

2. Create a 3X3 matrix with values ranging from 0 to 8.

{Hint:look for np.reshape()}

3. Create a 3X3 identity matrix.

{Hint:np.eye()}

4. Create a random array of size 30 and find the mean of the array.

{Hint:check for np.random.random() and array.mean() function}

5. Create a 10X10 array with random values and find the minimum and maximum values.

6. Create a zero array of size 10 and replace 5th element with 1.

7. Reverse an array arr = [1,2,0,0,4,0].

8. Create a 2d array with 1 on border and 0 inside.

9. Create a 8X8 matrix and fill it with a checkerboard pattern.


Problem - 3: Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:

1. Add the two array.

2. Subtract the two array.

3. Multiply the array with any integers of your choice.

4. Find the square of each element of the array.

5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

Problem - 4: Matrix Operations:

• For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

Prove following with Numpy:

1. Prove A.A−1 = I.

2. Prove AB ̸= BA.

3. Prove (AB)T = BTAT.


• Solve the following system of Linear equation using Inverse Methods.


2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9


{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}


• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [ ]:
## Problem 1: Array Creation
import numpy as np

# 1. Empty array 2x2
a = np.empty((2,2))
print("Empty array:\n", a)

# 2. Ones array 4x2
b = np.ones((4,2))
print("\nOnes array:\n", b)

# 3. Array filled with specific value
c = np.full((3,3), 7)
print("\nFull array:\n", c)

# 4. Zeros array like another array
d = np.zeros_like(c)
print("\nZeros like:\n", d)

# 5. Ones array like another array
e = np.ones_like(c)
print("\nOnes like:\n", e)

# 6. Convert list to numpy array
new_list = [1,2,3,4]
f = np.array(new_list)
print("\nArray from list:\n", f)

Empty array:
 [[4.04422213e-315 0.00000000e+000]
 [1.03867630e-152 6.20311190e+223]]

Ones array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Full array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros like:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

Ones like:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

Array from list:
 [1 2 3 4]


In [ ]:
##Problem 2: Array Manipulation
# 1. Array from 10 to 49
arr = np.arange(10,50)
print(arr)

# 2. 3x3 matrix from 0 to 8
mat = np.arange(9).reshape(3,3)
print(mat)

# 3. Identity matrix
I = np.eye(3)
print(I)

# 4. Random array of size 30 and mean
rand = np.random.random(30)
print(rand.mean())

# 5. 10x10 random array and min/max
r = np.random.random((10,10))
print("Min:", r.min(), "Max:", r.max())

# 6. Zero array and replace element
z = np.zeros(10)
z[4] = 1
print(z)

# 7. Reverse array
arr = np.array([1,2,0,0,4,0])
print(arr[::-1])

# 8. Border 1 and inside 0
border = np.ones((5,5))
border[1:-1,1:-1] = 0
print(border)

# 9. 8x8 checkerboard
checker = np.zeros((8,8))
checker[1::2,::2] = 1
checker[::2,1::2] = 1
print(checker)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
0.5590667825363965
Min: 0.012740992321603084 Max: 0.9991720955795239
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0 4 0 0 2 1]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
## Problem 3: Array Operations
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

# 1. Add
print(x + y)

# 2. Subtract
print(x - y)

# 3. Multiply by integer
print(x * 3)

# 4. Square each element
print(x ** 2)

# 5. Dot product
print("v.w =", np.dot(v,w))
print("x.v =", np.dot(x,v))
print("x.y =", np.dot(x,y))

# 6. Concatenate
print(np.vstack((x,y)))      # row
print(np.column_stack((v,w))) # column

# 7. Concatenate x and v
# np.concatenate((x,v))  → Error

[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 3  6]
 [ 9 15]]
[[ 1  4]
 [ 9 25]]
v.w = 219
x.v = [29 77]
x.y = [[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]


In [ ]:
## Problem 4: Matrix Operations
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1. A * A^-1 = I
A_inv = np.linalg.inv(A)
print(np.dot(A,A_inv))

# 2. AB ≠ BA
print("AB:\n", np.dot(A,B))
print("BA:\n", np.dot(B,A))

# 3. (AB)^T = B^T A^T
left = np.transpose(np.dot(A,B))
right = np.dot(np.transpose(B), np.transpose(A))
print(left)
print(right)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
[[23 51]
 [13 29]]
[[23 51]
 [13 29]]


In [ ]:
# Solving Linear Equations

## System
## 2x − 3y + z = −1
## x − y + 2z = −3
## 3x + y − z = 9

## Matrix form:
## AX = B

A = np.array([
[2,-3,1],
[1,-1,2],
[3,1,-1]
])

B = np.array([-1,-3,9])

# Using inverse method
A_inv = np.linalg.inv(A)

X = np.dot(A_inv,B)

print("Solution [x,y,z] =", X)

Solution [x,y,z] = [ 2.  1. -2.]


### **10.2 Experiment: How Fast is Numpy?**

In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:

1. Element-wise Addition:

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

3. Dot Product

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

4. Matrix Multiplication


• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.


• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

In [ ]:
import numpy as np
import time
import random

# size for vector operations
size = 1000000

# create python lists
list1 = [random.random() for _ in range(size)]
list2 = [random.random() for _ in range(size)]

# create numpy arrays
arr1 = np.array(list1)
arr2 = np.array(list2)


# 1. Element-wise Addition


# Python list addition
start = time.time()
result = [list1[i] + list2[i] for i in range(size)]
end = time.time()
print("Python list addition time:", end - start)

# NumPy addition
start = time.time()
result = arr1 + arr2
end = time.time()
print("NumPy addition time:", end - start)


# 2. Element-wise Multiplication


# Python list multiplication
start = time.time()
result = [list1[i] * list2[i] for i in range(size)]
end = time.time()
print("Python list multiplication time:", end - start)

# NumPy multiplication
start = time.time()
result = arr1 * arr2
end = time.time()
print("NumPy multiplication time:", end - start)


# 3. Dot Product


# Python list dot product
start = time.time()
dot = sum(list1[i] * list2[i] for i in range(size))
end = time.time()
print("Python list dot product time:", end - start)

# NumPy dot product
start = time.time()
dot = np.dot(arr1, arr2)
end = time.time()
print("NumPy dot product time:", end - start)


# 4. Matrix Multiplication


# smaller matrices recommended for Python lists
n = 200

A = [[random.random() for _ in range(n)] for _ in range(n)]
B = [[random.random() for _ in range(n)] for _ in range(n)]

# Python list matrix multiplication
start = time.time()

result = [[0]*n for _ in range(n)]

for i in range(n):
    for j in range(n):
        for k in range(n):
            result[i][j] += A[i][k] * B[k][j]

end = time.time()
print("Python matrix multiplication time:", end - start)

# NumPy matrices
A_np = np.array(A)
B_np = np.array(B)

start = time.time()
result = np.dot(A_np, B_np)
end = time.time()
print("NumPy matrix multiplication time:", end - start)

Python list addition time: 0.10352015495300293
NumPy addition time: 0.01687312126159668
Python list multiplication time: 0.10637021064758301
NumPy multiplication time: 0.01617145538330078
Python list dot product time: 0.08367633819580078
NumPy dot product time: 0.0016179084777832031
Python matrix multiplication time: 2.1192965507507324
NumPy matrix multiplication time: 0.005267143249511719
